# Generated by Django 3.2.7 on 2021-09-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userController', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(auto_created=True, max_length=25)),
                ('username', models.CharField(default='username', max_length=50)),
                ('password', models.CharField(default='password', max_length=25)),
                ('mail', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='user_login',
        ),
    ]
